//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab
    {
        public Lab()
        {
            this.People = new HashSet<Person>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> ClassID { get; set; }
        public int ScheduleId { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
