//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeekThreeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.Grades = new HashSet<Grades>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ScheduleId { get; set; }
        public int ClassFileId { get; set; }
    
        public virtual ICollection<Grades> Grades { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual ClassFile ClassFile { get; set; }
    }
}
