//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeekThreeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Activities = new HashSet<Activity>();
            this.Labs = new HashSet<Lab>();
        }
    
        public int Id { get; set; }
        public string DayoftheWeek { get; set; }
        public string Time { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<Lab> Labs { get; set; }
    }
}
